vim.keymap.set("n","te",function ()
   local r,c = unpack(vim.api.nvim_win_get_cursor(0))
   print(vim.fn.cindent(r))
end)
vim.keymap.set("n","fe",function ()
   local r,c = unpack(vim.api.nvim_win_get_cursor(0))
   print(vim.fn.lispindent(r))
end)
vim.keymap.set("n","we",function ()
   local r,c = unpack(vim.api.nvim_win_get_cursor(0))
   print(vim.fn.indent(r))
end)

